version: "3.5"
services:
  fluent:
    image: "ghcr.io/fluentlabs-xyz/fluent:v0.1.0-dev.2"
    command:
      - "--chain=developer-preview"
      - "node"
      - "--datadir=/datadir"
      - "--dev"
      - "--full"
      - "--http"
      - "--http.addr=0.0.0.0"
      - "--http.api=eth,net,web3,debug,trace,txpool"
      - "--http.port=8545"
      - "--http.corsdomain=*"
      - "--ws"
      - "--ws.addr=0.0.0.0"
      - "--ws.api=eth,net,web3,debug,trace,txpool"
      - "--ws.port=8546"
      - "--ws.origins=*"
    volumes:
      - "./datadir:/datadir"
    ports:
      - "8545:8545"
      - "8546:8546"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    restart: always
  faucet:
    image: chainflag/eth-faucet:1.1.0
    environment:
      WEB3_PROVIDER: "https://rpc.${DOMAIN_NAME}/"
      PRIVATE_KEY: "ac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
    restart: always
  relayer:
    image: fluentxyz/relayer:latest
    environment:
      L1_CONFIG_ENDPOINT: "https://ethereum-holesky-rpc.publicnode.com"
      L1_CONFIG_WS: "wss://ethereum-holesky-rpc.publicnode.com"
      L1_CONFIG_BRIDGE_ADDRESS: "0x26bDc9d2aA7BB9beE05ED737E16482D5718B02c3"
      L1_CONFIG_SIGNER: "e2d5c4f37c863ef55779345bb3725b63bb4e17b51f9e6cad2c0e57e39d7c7ff7"
      L2_CONFIG_ENDPOINT: "https://rpc.dev.thefluent.xyz/"
      L2_CONFIG_WS: "wss://rpc.dev.thefluent.xyz/ws"
      L2_CONFIG_BRIDGE_ADDRESS: "0x6Ff08946Cef705D7bBC5deef4E56004e2365979f"
      L2_CONFIG_SIGNER: "e2d5c4f37c863ef55779345bb3725b63bb4e17b51f9e6cad2c0e57e39d7c7ff7"
      RELAYER_ENABLED: "true"
      DA_ENABLED: "false"
      CELESTIA_ENABLED: "false"
      EIGEN_ENABLED: "false"
      AVAIL_ENABLED: "false"
      RELAYER_REDIS_ENDPOINT: "172.17.0.1:6379"
    restart: always
  nginx:
    build: "./nginx"
    environment:
      DOMAIN_NAME: "${DOMAIN_NAME}"
    volumes:
      - /root/.acme.sh/:/root/.acme.sh/
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - "443:443"
      - "80:80"
    restart: always
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ~/redis/d–∞ta:/root/redis